openapi: 3.0.0
info:
  title: Wallet Financial API Service
  description: API service for managing financial assets
  version: 1.0.0
servers:
  - url: http://localhost:8083
paths:
  /v1/assets:
    get:
      summary: Retrieve a list of assets
      parameters:
        - name: user_id
          in: query
          description: ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                - user_id: 1
                  name: "AAPL"
                  type: "stock"
                  quantity: 100
                  value: 150.25
                  purchase_on: "2023-09-15"
    post:
      summary: Create a new asset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ID of the user
                name:
                  type: string
                  description: Name of the asset
                type:
                  type: string
                  enum: ['stock', 'crypto', 'commodity', 'other']
                  description: Type of the asset
                quantity:
                  type: number
                  description: Quantity of the asset
                value:
                  type: number
                  description: Value of the asset
                purchase_on:
                  type: string
                  format: date
                  description: Purchase date of the asset (YYYY-MM-DD)
              required:
                - user_id
                - name
                - type
                - quantity
                - value
                - purchase_on
            examples:
              example1:
                value:
                  user_id: 1
                  name: "AAPL"
                  type: "stock"
                  quantity: 100
                  value: 150.25
                  purchase_on: "2023-09-15"
      responses:
        '201':
          description: Asset created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    description: ID of the user
                  name:
                    type: string
                    description: Name of the asset
                  type:
                    type: string
                    enum: ['stock', 'crypto', 'commodity', 'other']
                    description: Type of the asset
                  quantity:
                    type: number
                    description: Quantity of the asset
                  value:
                    type: number
                    description: Value of the asset
                  purchase_on:
                    type: string
                    format: date
                    description: Purchase date of the asset (YYYY-MM-DD)
              example:
                user_id: 1
                name: "AAPL"
                type: "stock"
                quantity: 100
                value: 150.25
                purchase_on: "2023-09-15"
  /v1/assets/{asset_id}:
    get:
      summary: Retrieve an asset by ID
      parameters:
        - name: asset_id
          in: path
          description: ID of the asset
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                user_id: 1
                name: "AAPL"
                type: "stock"
                quantity: 100
                value: 150.25
                purchase_on: "2023-09-15"
        '404':
          description: Asset not found
          content:
            application/json:
              example:
                error: "asset not found"
    put:
      summary: Update an existing asset
      parameters:
        - name: asset_id
          in: path
          description: ID of the asset
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: ID of the user
                name:
                  type: string
                  description: Name of the asset
                type:
                  type: string
                  enum: ['stock', 'crypto', 'commodity', 'other']
                  description: Type of the asset
                quantity:
                  type: number
                  description: Quantity of the asset
                value:
                  type: number
                  description: Value of the asset
                purchase_on:
                  type: string
                  format: date
                  description: Purchase date of the asset (YYYY-MM-DD)
              required:
                - user_id
                - name
                - type
                - quantity
                - value
                - purchase_on
            examples:
              example1:
                value:
                  user_id: 1
                  name: "AAPL"
                  type: "stock"
                  quantity: 100
                  value: 150.25
                  purchase_on: "2023-09-15"
      responses:
        '200':
          description: Asset updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    description: ID of the user
                  name:
                    type: string
                    description: Name of the asset
                  type:
                    type: string
                    enum: ['stock', 'crypto', 'commodity', 'other']
                    description: Type of the asset
                  quantity:
                    type: number
                    description: Quantity of the asset
                  value:
                    type: number
                    description: Value of the asset
                  purchase_on:
                    type: string
                    format: date
                    description: Purchase date of the asset (YYYY-MM-DD)
              example:
                user_id: 1
                name: "AAPL"
                type: "stock"
                quantity: 100
                value: 150.25
                purchase_on: "2023-09-15"
    delete:
      summary: Delete an asset by ID
      parameters:
        - name: asset_id
          in: path
          description: ID of the asset
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Asset deleted successfully
          content:
            application/json:
              example:
                message: "asset deleted"
        '404':
          description: Asset not found
          content:
            application/json:
              example:
                error: "asset not found"
