openapi: 3.0.0
info:
  title: Wallet User Identity API
  version: 1.0.0
servers:
  - url: http://localhost:8083
paths:
  /v1/login:
    post:
      summary: Authenticate user and get access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user.
                  example: diego 
                password:
                  type: string
                  description: The user's password.
                  example: diego 
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: The generated access token.
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '400':
          description: Bad request
        '401':
          description: Unauthorized
      tags:
        - login

  /v1/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the new user.
                  example: jane_doe
                password:
                  type: string
                  description: The password for the new user.
                  example: myothersecretpassword
                email:
                  type: string
                  format: email
                  description: The email address of the new user.
                  example: jane@example.com
      responses:
        '200':
          description: User created successfully
        '400':
          description: Bad request
        '409':
          description: User already exists
        '500':
          description: Internal server error

      tags:
        - register 
  /v1/token/validate:
    post:
      summary: Validate access token
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Token is valid
        '401':
          description: Unauthorized
      tags:
        - token 

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
